#!/bin/bash

shopt -s nullglob globstar

STORE_DIR=${PASSWORD_STORE_DIR:-~/.password-store}

password_files=( ${STORE_DIR}/**/*.gpg )
password_files=( "${password_files[@]##${STORE_DIR}/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

pass -c "$password"
